services:
  mongo: 
    image : mongo
    ports :
      - "27017:27017"

  backend:
    build : ./Backend
    container_name: backend
    env_file:
      - "./Backend/.env.prod"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  
  frontend:
    build : ./Frontend/todo-app
    container_name: frontend
    env_file:
      - "./Frontend/todo-app/.env.prod"
    ports:
      - "3000:3000"
    depends_on:
      - backend